name: release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  # Sanity check that main isn't broken
  test:
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python '3.10'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install poetry
      run: |
        curl -sSL \
          "https://install.python-poetry.org" | python -
        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    
    - name: Build artifact
      run: |
        poetry config virtualenvs.in-project true
        poetry build -n

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ github.workspace }}/dist
        retention-days: 1
        if-no-files-found: error

    - name: Publish to Pypi
      run: |
        poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Download artifacts
      id: artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          ${{ steps.artifacts.outputs.download-path }}/dist/*

# For some reason twine complains `long_description` has syntax errors in markup and would not be rendered on PyPI
#   publish:
#     runs-on: ubuntu-latest
#     needs:
#       - build

#     steps:
#     - name: Download artifacts
#       id: artifacts
#       uses: actions/download-artifact@v4

#     - name: Publish to pypi
#       uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         packages_dir: ${{ steps.artifacts.outputs.download-path }}/dist/
#         password: ${{ secrets.PYPI_API_TOKEN }}

